const productos = [
  {
    id: 1,
    nombre: "Año de las despedidas",
    autor: "Rosario M. Pérez",
    precio: 50,
    img: "https://th.bing.com/th/id/OIP.RCwQynagIg0KG2qCKKWwtgAAAA?pid=ImgDet&w=376&h=601&rs=1",
    cantidad: 1,
  },
  {
    id: 2,
    nombre: "Memorias del Sáhara",
    autor: "Nairobi L. Vowels",
    precio: 100,
    img: "https://th.bing.com/th/id/OIP.e1YtwVXYIKFejFQ45fbCbAHaL0?rs=1&pid=ImgDetMain",
    cantidad: 1,
  },
  {
    id: 3,
    nombre: "Decide Vivir",
    autor: "Rodolfo Martín",
    precio: 150,
    img: "https://th.bing.com/th/id/OIP.AjeN3U9sSQyVTzNe7PZN0QAAAA?pid=ImgDet&w=376&h=601&rs=1",
    cantidad: 1,
  },
  {
    id: 4,
    nombre: "Era de imperios",
    autor: "Leonardo Zambrano",
    precio: 200,
    img: "https://th.bing.com/th/id/OIP.gJGyAdBTR7XGEGTwCvnxTwAAAA?pid=ImgDet&w=376&h=601&rs=1",
    cantidad: 1,
  },
  {
    id: 5,
    nombre: "El otro silencio",
    autor: "María Garcia",
    precio: 250,
    img: "https://th.bing.com/th/id/OIP.v1vHSSpCyRcbZE7tYiBwfgAAAA?pid=ImgDet&w=376&h=601&rs=1",
    cantidad: 1,
  },
];
